stages:
  dataingestion:
    cmd: python src/dataingestion.py
    deps:
    - src/dataingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/datapreprocessing.py
    deps:
    - data/raw
    - src/datapreprocessing.py
    outs:
    - data/preprocessed
  FeatureEngineering:
    cmd: python src/featureEngineering.py
    deps:
    - data/preprocessed
    - src/featureEngineering.py
    outs:
    - data/Featurestored
