stages:
  dataingestion:
    cmd: python src/dataingestion.py
    deps:
    - src/dataingestion.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/datapreprocessing.py
    deps:
    - data/raw
    - src/datapreprocessing.py
    outs:
    - data/preprocessed
  FeatureEngineering:
    cmd: python src/featureEngineering.py
    deps:
    - data/preprocessed
    - src/featureEngineering.py
    outs:
    - data/Featurestored
  model_building:
    cmd: python src/modelBuilding.py
    deps:
    - data/Featurestored
    - src/modelBuilding.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/featurestored/testBow.csv
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json:
        cache: false
